name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/download-artifact@v3
        name: 'Fetch coverage from builds'
        with:
          name: coverage
          path: coverage.xml

      - uses: codecov/codecov-action@v4
        name: Upload coverage report
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
